package dev.eness.sololevelingfinal.core.init;

import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import dev.eness.sololevelingfinal.core.block.BeastRubbleBlock;
import dev.eness.sololevelingfinal.core.block.CellDoorClosedBlock;
import dev.eness.sololevelingfinal.core.block.CellDoorOpenBlock;
import dev.eness.sololevelingfinal.core.block.CrystalGolemSpawnerBlock;
import dev.eness.sololevelingfinal.core.block.CustomPortalBlock;
import dev.eness.sololevelingfinal.core.block.DeepslateKeyblockBlock;
import dev.eness.sololevelingfinal.core.block.DeepslateKeyblockBlueBlock;
import dev.eness.sololevelingfinal.core.block.DeepslateKeyblockDKCBlock;
import dev.eness.sololevelingfinal.core.block.DeepslateKeyblockRedBlock;
import dev.eness.sololevelingfinal.core.block.DisappearingBlockBlock;
import dev.eness.sololevelingfinal.core.block.DungeonBarrelBlock;
import dev.eness.sololevelingfinal.core.block.DungeonBlock2Block;
import dev.eness.sololevelingfinal.core.block.DungeonBlockBlock;
import dev.eness.sololevelingfinal.core.block.DungeonBricksBlock;
import dev.eness.sololevelingfinal.core.block.DungeonFloorBlock;
import dev.eness.sololevelingfinal.core.block.DungeonGrave1Block;
import dev.eness.sololevelingfinal.core.block.DungeonGrave2Block;
import dev.eness.sololevelingfinal.core.block.DungeonToolsBlock;
import dev.eness.sololevelingfinal.core.block.DungeonWallBlock;
import dev.eness.sololevelingfinal.core.block.DungeonWallSmallBlock;
import dev.eness.sololevelingfinal.core.block.EvaluatorTestBlock;
import dev.eness.sololevelingfinal.core.block.FrostCausewayBlock;
import dev.eness.sololevelingfinal.core.block.GoblinSpawnerBlock;
import dev.eness.sololevelingfinal.core.block.GolemDropBlockGemBlock;
import dev.eness.sololevelingfinal.core.block.GuildComputerBlock;
import dev.eness.sololevelingfinal.core.block.HunterRankEvaluatorBlock;
import dev.eness.sololevelingfinal.core.block.InstanceCoverBlock;
import dev.eness.sololevelingfinal.core.block.InstanceDungeonKeyLoggerBlock;
import dev.eness.sololevelingfinal.core.block.ManaCrystalDepositBlock;
import dev.eness.sololevelingfinal.core.block.PassageWallBlock;
import dev.eness.sololevelingfinal.core.block.ShadowBlock;
import dev.eness.sololevelingfinal.core.block.SkeletonBlock;
import dev.eness.sololevelingfinal.core.block.UnbreakableDeepslateBlock;
import dev.eness.sololevelingfinal.core.block.WoodenPassageOpenBlock;

public class SololevelingModBlocks {
   public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, "sololeveling");
   public static final RegistryObject<Block> DUNGEON_BLOCK = REGISTRY.register("dungeon_block", () -> new DungeonBlockBlock());
   public static final RegistryObject<Block> DUNGEON_BLOCK_2 = REGISTRY.register("dungeon_block_2", () -> new DungeonBlock2Block());
   public static final RegistryObject<Block> GOBLIN_SPAWNER = REGISTRY.register("goblin_spawner", () -> new GoblinSpawnerBlock());
   public static final RegistryObject<Block> DISAPPEARING_BLOCK = REGISTRY.register("disappearing_block", () -> new DisappearingBlockBlock());
   public static final RegistryObject<Block> UNBREAKABLE_DEEPSLATE = REGISTRY.register("unbreakable_deepslate", () -> new UnbreakableDeepslateBlock());
   public static final RegistryObject<Block> DEEPSLATE_KEYBLOCK = REGISTRY.register("deepslate_keyblock", () -> new DeepslateKeyblockBlock());
   public static final RegistryObject<Block> DEEPSLATE_KEYBLOCK_BLUE = REGISTRY.register("deepslate_keyblock_blue", () -> new DeepslateKeyblockBlueBlock());
   public static final RegistryObject<Block> DEEPSLATE_KEYBLOCK_RED = REGISTRY.register("deepslate_keyblock_red", () -> new DeepslateKeyblockRedBlock());
   public static final RegistryObject<Block> CRYSTAL_GOLEM_SPAWNER = REGISTRY.register("crystal_golem_spawner", () -> new CrystalGolemSpawnerBlock());
   public static final RegistryObject<Block> GOLEM_DROP_BLOCK_GEM = REGISTRY.register("golem_drop_block_gem", () -> new GolemDropBlockGemBlock());
   public static final RegistryObject<Block> MANA_CRYSTAL_DEPOSIT = REGISTRY.register("mana_crystal_deposit", ManaCrystalDepositBlock::new);
   public static final RegistryObject<Block> INSTANCE_DUNGEON_KEY_LOGGER = REGISTRY.register(
      "instance_dungeon_key_logger", () -> new InstanceDungeonKeyLoggerBlock()
   );
   public static final RegistryObject<Block> INSTANCE_COVER = REGISTRY.register("instance_cover", () -> new InstanceCoverBlock());
   public static final RegistryObject<Block> HUNTER_RANK_EVALUATOR = REGISTRY.register("hunter_rank_evaluator", () -> new HunterRankEvaluatorBlock());
   public static final RegistryObject<Block> WOODEN_PASSAGE_OPEN = REGISTRY.register("wooden_passage_open", () -> new WoodenPassageOpenBlock());
   public static final RegistryObject<Block> CELL_DOOR_CLOSED = REGISTRY.register("cell_door_closed", () -> new CellDoorClosedBlock());
   public static final RegistryObject<Block> DUNGEON_FLOOR = REGISTRY.register("dungeon_floor", () -> new DungeonFloorBlock());
   public static final RegistryObject<Block> DUNGEON_BRICKS = REGISTRY.register("dungeon_bricks", () -> new DungeonBricksBlock());
   public static final RegistryObject<Block> CELL_DOOR_OPEN = REGISTRY.register("cell_door_open", () -> new CellDoorOpenBlock());
   public static final RegistryObject<Block> DUNGEON_WALL_SMALL = REGISTRY.register("dungeon_wall_small", () -> new DungeonWallSmallBlock());
   public static final RegistryObject<Block> DUNGEON_BARREL = REGISTRY.register("dungeon_barrel", () -> new DungeonBarrelBlock());
   public static final RegistryObject<Block> DUNGEON_TOOLS = REGISTRY.register("dungeon_tools", () -> new DungeonToolsBlock());
   public static final RegistryObject<Block> SKELETON = REGISTRY.register("skeleton", () -> new SkeletonBlock());
   public static final RegistryObject<Block> DUNGEON_GRAVE_1 = REGISTRY.register("dungeon_grave_1", () -> new DungeonGrave1Block());
   public static final RegistryObject<Block> DUNGEON_GRAVE_2 = REGISTRY.register("dungeon_grave_2", () -> new DungeonGrave2Block());
   public static final RegistryObject<Block> PASSAGE_WALL = REGISTRY.register("passage_wall", () -> new PassageWallBlock());
   public static final RegistryObject<Block> DUNGEON_WALL = REGISTRY.register("dungeon_wall", () -> new DungeonWallBlock());
   public static final RegistryObject<Block> EVALUATOR_TEST = REGISTRY.register("evaluator_test", () -> new EvaluatorTestBlock());
   public static final RegistryObject<Block> CUSTOM_PORTAL = REGISTRY.register("custom_portal", () -> new CustomPortalBlock());
   public static final RegistryObject<Block> SHADOW = REGISTRY.register("shadow", () -> new ShadowBlock());
   public static final RegistryObject<Block> DEEPSLATE_KEYBLOCK_DKC = REGISTRY.register("deepslate_keyblock_dkc", () -> new DeepslateKeyblockDKCBlock());
   public static final RegistryObject<Block> FROST_CAUSEWAY = REGISTRY.register("frost_causeway", FrostCausewayBlock::new);
   public static final RegistryObject<Block> BEAST_RUBBLE = REGISTRY.register("beast_rubble", BeastRubbleBlock::new);
   public static final RegistryObject<Block> GUILD_COMPUTER = REGISTRY.register("guild_computer", GuildComputerBlock::new);
}
