package dev.eness.sololevelingfinal.core.init;

import net.minecraft.world.effect.MobEffect;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import dev.eness.sololevelingfinal.core.potion.AirVacuumCooldwonMobEffect;
import dev.eness.sololevelingfinal.core.potion.AriseCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.ArrowRainCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.AuraCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.AuraMobEffect;
import dev.eness.sololevelingfinal.core.potion.BackstabCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.BellOfHealingCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.BleedMobEffect;
import dev.eness.sololevelingfinal.core.potion.BloodlustCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.ConsecutiveSlashesMobEffect;
import dev.eness.sololevelingfinal.core.potion.CooldownSOFFMobEffect;
import dev.eness.sololevelingfinal.core.potion.CounterCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.CriticalStrikeCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.CrossAttackCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.CurseSmokeCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.CursedChainsCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.DaggerRushCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.DanceCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.DashcooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.DetectionCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.DomainBoostMobEffect;
import dev.eness.sololevelingfinal.core.potion.DualWieldingCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.DualWieldingMobEffect;
import dev.eness.sololevelingfinal.core.potion.ElderBeastCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.FatigueCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.FocusCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.FortifyMobEffect;
import dev.eness.sololevelingfinal.core.potion.FragOfProtectionCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.FreezeMobEffect;
import dev.eness.sololevelingfinal.core.potion.GolemKickCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.GolemTeleportCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.HasteBuffCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.HasteBuffMobEffect;
import dev.eness.sololevelingfinal.core.potion.HawkeyeCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.HealingBeamCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.HeavyImpactCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.HomingFlameCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.ImpactRushCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.JobCooldown1MobEffect;
import dev.eness.sololevelingfinal.core.potion.JobCooldown2MobEffect;
import dev.eness.sololevelingfinal.core.potion.JobCooldown3MobEffect;
import dev.eness.sololevelingfinal.core.potion.JobCooldown4MobEffect;
import dev.eness.sololevelingfinal.core.potion.KamishcoolMobEffect;
import dev.eness.sololevelingfinal.core.potion.LeapCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.LevDaggerCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.LightballCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.ManaRefleshCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.MasteryCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.MutilationStatusEffectMobEffect;
import dev.eness.sololevelingfinal.core.potion.NoFallDamageMobEffect;
import dev.eness.sololevelingfinal.core.potion.OverHealAOEMobEffect;
import dev.eness.sololevelingfinal.core.potion.OverHealCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.OverHealEffectMobEffect;
import dev.eness.sololevelingfinal.core.potion.ParalyzeCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.ParalyzeMobEffect;
import dev.eness.sololevelingfinal.core.potion.PhysicalBuffCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.PhysicalBuffMobEffect;
import dev.eness.sololevelingfinal.core.potion.QuickSlashesCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.SOLcooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.ScreenShakeMobEffect;
import dev.eness.sololevelingfinal.core.potion.ShadowStepCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.ShieldBashCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.ShieldBashEffectMobEffect;
import dev.eness.sololevelingfinal.core.potion.SpearCreationCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.StealthCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.SwordDanceCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.SwordDanceMobEffect;
import dev.eness.sololevelingfinal.core.potion.SwordEnhanceMobEffect;
import dev.eness.sololevelingfinal.core.potion.SwordOfLightMobEffect;
import dev.eness.sololevelingfinal.core.potion.TankInvCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.TauntCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.TelekinesisCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.TiemrMobEffect;
import dev.eness.sololevelingfinal.core.potion.TrapCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.UpforceSlashCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.UsingFireMobEffect;
import dev.eness.sololevelingfinal.core.potion.WaterBulletCooldownMobEffect;
import dev.eness.sololevelingfinal.core.potion.WillPowerMobEffect;
import dev.eness.sololevelingfinal.core.potion.WillpowerCooldownMobEffect;

public class SololevelingModMobEffects {
   public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(ForgeRegistries.MOB_EFFECTS, "sololeveling");
   public static final RegistryObject<MobEffect> PARALYZE = REGISTRY.register("paralyze", () -> new ParalyzeMobEffect());
   public static final RegistryObject<MobEffect> BLEED = REGISTRY.register("bleed", () -> new BleedMobEffect());
   public static final RegistryObject<MobEffect> COOLDOWN_SOFF = REGISTRY.register("cooldown_soff", () -> new CooldownSOFFMobEffect());
   public static final RegistryObject<MobEffect> PARALYZE_COOLDOWN = REGISTRY.register("paralyze_cooldown", () -> new ParalyzeCooldownMobEffect());
   public static final RegistryObject<MobEffect> DAGGER_RUSH_COOLDOWN = REGISTRY.register("dagger_rush_cooldown", () -> new DaggerRushCooldownMobEffect());
   public static final RegistryObject<MobEffect> SWORD_ENHANCE = REGISTRY.register("sword_enhance", () -> new SwordEnhanceMobEffect());
   public static final RegistryObject<MobEffect> KAMISHCOOL = REGISTRY.register("kamishcool", () -> new KamishcoolMobEffect());
   public static final RegistryObject<MobEffect> COUNTER_COOLDOWN = REGISTRY.register("counter_cooldown", () -> new CounterCooldownMobEffect());
   public static final RegistryObject<MobEffect> STEALTH_COOLDOWN = REGISTRY.register("stealth_cooldown", () -> new StealthCooldownMobEffect());
   public static final RegistryObject<MobEffect> BLOODLUST_COOLDOWN = REGISTRY.register("bloodlust_cooldown", () -> new BloodlustCooldownMobEffect());
   public static final RegistryObject<MobEffect> WATER_BULLET_COOLDOWN = REGISTRY.register("water_bullet_cooldown", () -> new WaterBulletCooldownMobEffect());
   public static final RegistryObject<MobEffect> IMPACT_RUSH_COOLDOWN = REGISTRY.register("impact_rush_cooldown", () -> new ImpactRushCooldownMobEffect());
   public static final RegistryObject<MobEffect> HEAVY_IMPACT_COOLDOWN = REGISTRY.register("heavy_impact_cooldown", () -> new HeavyImpactCooldownMobEffect());
   public static final RegistryObject<MobEffect> ARISE_COOLDOWN = REGISTRY.register("arise_cooldown", () -> new AriseCooldownMobEffect());
   public static final RegistryObject<MobEffect> CONSECUTIVE_SLASHES = REGISTRY.register("consecutive_slashes", () -> new ConsecutiveSlashesMobEffect());
   public static final RegistryObject<MobEffect> TANK_INV_COOLDOWN = REGISTRY.register("tank_inv_cooldown", () -> new TankInvCooldownMobEffect());
   public static final RegistryObject<MobEffect> FRAG_OF_PROTECTION_COOLDOWN = REGISTRY.register(
      "frag_of_protection_cooldown", () -> new FragOfProtectionCooldownMobEffect()
   );
   public static final RegistryObject<MobEffect> LEAP_COOLDOWN = REGISTRY.register("leap_cooldown", () -> new LeapCooldownMobEffect());
   public static final RegistryObject<MobEffect> HEALING_BEAM_COOLDOWN = REGISTRY.register("healing_beam_cooldown", () -> new HealingBeamCooldownMobEffect());
   public static final RegistryObject<MobEffect> OVER_HEAL_EFFECT = REGISTRY.register("over_heal_effect", () -> new OverHealEffectMobEffect());
   public static final RegistryObject<MobEffect> OVER_HEAL_COOLDOWN = REGISTRY.register("over_heal_cooldown", () -> new OverHealCooldownMobEffect());
   public static final RegistryObject<MobEffect> BELL_OF_HEALING_COOLDOWN = REGISTRY.register(
      "bell_of_healing_cooldown", () -> new BellOfHealingCooldownMobEffect()
   );
   public static final RegistryObject<MobEffect> MANA_REFLESH_COOLDOWN = REGISTRY.register("mana_reflesh_cooldown", () -> new ManaRefleshCooldownMobEffect());
   public static final RegistryObject<MobEffect> USING_FIRE = REGISTRY.register("using_fire", () -> new UsingFireMobEffect());
   public static final RegistryObject<MobEffect> HOMING_FLAME_COOLDOWN = REGISTRY.register("homing_flame_cooldown", () -> new HomingFlameCooldownMobEffect());
   public static final RegistryObject<MobEffect> LEV_DAGGER_COOLDOWN = REGISTRY.register("lev_dagger_cooldown", () -> new LevDaggerCooldownMobEffect());
   public static final RegistryObject<MobEffect> TELEKINESIS_COOLDOWN = REGISTRY.register("telekinesis_cooldown", () -> new TelekinesisCooldownMobEffect());
   public static final RegistryObject<MobEffect> AIR_VACUUM_COOLDWON = REGISTRY.register("air_vacuum_cooldwon", () -> new AirVacuumCooldwonMobEffect());
   public static final RegistryObject<MobEffect> JOB_COOLDOWN_1 = REGISTRY.register("job_cooldown_1", () -> new JobCooldown1MobEffect());
   public static final RegistryObject<MobEffect> JOB_COOLDOWN_2 = REGISTRY.register("job_cooldown_2", () -> new JobCooldown2MobEffect());
   public static final RegistryObject<MobEffect> JOB_COOLDOWN_3 = REGISTRY.register("job_cooldown_3", () -> new JobCooldown3MobEffect());
   public static final RegistryObject<MobEffect> JOB_COOLDOWN_4 = REGISTRY.register("job_cooldown_4", () -> new JobCooldown4MobEffect());
   public static final RegistryObject<MobEffect> CROSS_ATTACK_COOLDOWN = REGISTRY.register("cross_attack_cooldown", () -> new CrossAttackCooldownMobEffect());
   public static final RegistryObject<MobEffect> DOMAIN_BOOST = REGISTRY.register("domain_boost", () -> new DomainBoostMobEffect());
   public static final RegistryObject<MobEffect> AURA = REGISTRY.register("aura", () -> new AuraMobEffect());
   public static final RegistryObject<MobEffect> DUAL_WIELDING = REGISTRY.register("dual_wielding", () -> new DualWieldingMobEffect());
   public static final RegistryObject<MobEffect> TIEMR = REGISTRY.register("tiemr", () -> new TiemrMobEffect());
   public static final RegistryObject<MobEffect> ELDER_BEAST_COOLDOWN = REGISTRY.register("elder_beast_cooldown", () -> new ElderBeastCooldownMobEffect());
   public static final RegistryObject<MobEffect> LIGHTBALL_COOLDOWN = REGISTRY.register("lightball_cooldown", () -> new LightballCooldownMobEffect());
   public static final RegistryObject<MobEffect> DETECTION_COOLDOWN = REGISTRY.register("detection_cooldown", () -> new DetectionCooldownMobEffect());
   public static final RegistryObject<MobEffect> UPFORCE_SLASH_COOLDOWN = REGISTRY.register("upforce_slash_cooldown", () -> new UpforceSlashCooldownMobEffect());
   public static final RegistryObject<MobEffect> QUICK_SLASHES_COOLDOWN = REGISTRY.register("quick_slashes_cooldown", () -> new QuickSlashesCooldownMobEffect());
   public static final RegistryObject<MobEffect> SHIELD_BASH_EFFECT = REGISTRY.register("shield_bash_effect", () -> new ShieldBashEffectMobEffect());
   public static final RegistryObject<MobEffect> NO_FALL_DAMAGE = REGISTRY.register("no_fall_damage", () -> new NoFallDamageMobEffect());
   public static final RegistryObject<MobEffect> SWORD_OF_LIGHT = REGISTRY.register("sword_of_light", () -> new SwordOfLightMobEffect());
   public static final RegistryObject<MobEffect> SWORD_DANCE = REGISTRY.register("sword_dance", () -> new SwordDanceMobEffect());
   public static final RegistryObject<MobEffect> DANCE_COOLDOWN = REGISTRY.register("dance_cooldown", () -> new DanceCooldownMobEffect());
   public static final RegistryObject<MobEffect> SO_LCOOLDOWN = REGISTRY.register("so_lcooldown", () -> new SOLcooldownMobEffect());
   public static final RegistryObject<MobEffect> OVER_HEAL_AOE = REGISTRY.register("over_heal_aoe", () -> new OverHealAOEMobEffect());
   public static final RegistryObject<MobEffect> PHYSICAL_BUFF = REGISTRY.register("physical_buff", () -> new PhysicalBuffMobEffect());
   public static final RegistryObject<MobEffect> HASTE_BUFF = REGISTRY.register("haste_buff", () -> new HasteBuffMobEffect());
   public static final RegistryObject<MobEffect> PHYSICAL_BUFF_COOLDOWN = REGISTRY.register("physical_buff_cooldown", () -> new PhysicalBuffCooldownMobEffect());
   public static final RegistryObject<MobEffect> HASTE_BUFF_COOLDOWN = REGISTRY.register("haste_buff_cooldown", () -> new HasteBuffCooldownMobEffect());
   public static final RegistryObject<MobEffect> WILL_POWER = REGISTRY.register("will_power", () -> new WillPowerMobEffect());
   public static final RegistryObject<MobEffect> AURA_COOLDOWN = REGISTRY.register("aura_cooldown", () -> new AuraCooldownMobEffect());
   public static final RegistryObject<MobEffect> SHADOW_STEP_COOLDOWN = REGISTRY.register("shadow_step_cooldown", () -> new ShadowStepCooldownMobEffect());
   public static final RegistryObject<MobEffect> DUAL_WIELDING_COOLDOWN = REGISTRY.register("dual_wielding_cooldown", () -> new DualWieldingCooldownMobEffect());
   public static final RegistryObject<MobEffect> BACKSTAB_COOLDOWN = REGISTRY.register("backstab_cooldown", () -> new BackstabCooldownMobEffect());
   public static final RegistryObject<MobEffect> SWORD_DANCE_COOLDOWN = REGISTRY.register("sword_dance_cooldown", () -> new SwordDanceCooldownMobEffect());
   public static final RegistryObject<MobEffect> WILLPOWER_COOLDOWN = REGISTRY.register("willpower_cooldown", () -> new WillpowerCooldownMobEffect());
   public static final RegistryObject<MobEffect> SHIELD_BASH_COOLDOWN = REGISTRY.register("shield_bash_cooldown", () -> new ShieldBashCooldownMobEffect());
   public static final RegistryObject<MobEffect> TAUNT_COOLDOWN = REGISTRY.register("taunt_cooldown", () -> new TauntCooldownMobEffect());
   public static final RegistryObject<MobEffect> FREEZE = REGISTRY.register("freeze", () -> new FreezeMobEffect());
   public static final RegistryObject<MobEffect> GOLEM_TELEPORT_COOLDOWN = REGISTRY.register(
      "golem_teleport_cooldown", () -> new GolemTeleportCooldownMobEffect()
   );
   public static final RegistryObject<MobEffect> GOLEM_KICK_COOLDOWN = REGISTRY.register("golem_kick_cooldown", () -> new GolemKickCooldownMobEffect());
   public static final RegistryObject<MobEffect> TRAP_COOLDOWN = REGISTRY.register("trap_cooldown", () -> new TrapCooldownMobEffect());
   public static final RegistryObject<MobEffect> HAWKEYE_COOLDOWN = REGISTRY.register("hawkeye_cooldown", () -> new HawkeyeCooldownMobEffect());
   public static final RegistryObject<MobEffect> FOCUS_COOLDOWN = REGISTRY.register("focus_cooldown", () -> new FocusCooldownMobEffect());
   public static final RegistryObject<MobEffect> ARROW_RAIN_COOLDOWN = REGISTRY.register("arrow_rain_cooldown", () -> new ArrowRainCooldownMobEffect());
   public static final RegistryObject<MobEffect> SPEAR_CREATION_COOLDOWN = REGISTRY.register(
      "spear_creation_cooldown", () -> new SpearCreationCooldownMobEffect()
   );
   public static final RegistryObject<MobEffect> SCREEN_SHAKE = REGISTRY.register("screen_shake", () -> new ScreenShakeMobEffect());
   public static final RegistryObject<MobEffect> DASHCOOLDOWN = REGISTRY.register("dashcooldown", () -> new DashcooldownMobEffect());
   public static final RegistryObject<MobEffect> FATIGUE_COOLDOWN = REGISTRY.register("fatigue_cooldown", () -> new FatigueCooldownMobEffect());
   public static final RegistryObject<MobEffect> MASTERY_COOLDOWN = REGISTRY.register("mastery_cooldown", () -> new MasteryCooldownMobEffect());
   public static final RegistryObject<MobEffect> CURSE_SMOKE_COOLDOWN = REGISTRY.register("curse_smoke_cooldown", () -> new CurseSmokeCooldownMobEffect());
   public static final RegistryObject<MobEffect> CURSED_CHAINS_COOLDOWN = REGISTRY.register("cursed_chains_cooldown", () -> new CursedChainsCooldownMobEffect());
   public static final RegistryObject<MobEffect> CRITICAL_STRIKE_COOLDOWN = REGISTRY.register(
      "critical_strike_cooldown", () -> new CriticalStrikeCooldownMobEffect()
   );
   public static final RegistryObject<MobEffect> MUTILATION_STATUS_EFFECT = REGISTRY.register(
      "mutilation_status_effect", () -> new MutilationStatusEffectMobEffect()
   );
   public static final RegistryObject<MobEffect> FORTIFY = REGISTRY.register("fortify", () -> new FortifyMobEffect());
}
